### ISSUE TITLE
Amélioration

### ISSUE THREAD

**Issue by Vebryn** [thibdct/programmateur-fil-pilote-wifi#2]
Bonsoir,

Excellent projet ! Bravo !

Un transistor NPN pour la commande des optocoupleurs sécuriserait les ports GPIO du MIC, je sais pas ce que t'en pense ?

Vebryn

**Comment by hallard** [comment]
Bonjour Vebryn,

Dans la version Hard 1.2, les optos sont commandés par un MCP23017, le courant de commande est d'environ (3.3V-1.4V) soit 1.9V / 470 ohm soit 4 mA
les ports du MCP sont limités à 25mA/port avec une conso maximale du MCP limité à 125mA
Si les 14 optos sont actifs nous sommes a 56mA donc largement dans la plage de fonctionnement.
Je viens dans le doute de vérifier sur la Version 1, les pins du core sont au max 20mA/pin et un total de 150mA pour le core, donc pour moi aucun soucis.
Ceci dit, j'ai peut-être raté quelque chose, si c'est le cas je veux bien savoir, au contraire.

**Comment by Vebryn** [comment]
Autant pour moi, merci pour tes lumières! Je réfléchi à adapter ton bébé à un Raspberry Pi. L'essentiel est là!

**Comment by hallard** [comment]
Rendons à César ce qui est à César, ce n'est pas mon bébé mais celui de Thibault ;-)
J'ai juste participé aux nouvelles fonctionnalités de la V1.2 

Ceci dit tu n'es pas le 1er à vouloir commander les fils pilotes avec un Pi.
- Soit il faut développer un shield spécifique
- Soit tu attaques le Remora avec des requêtes HTTP depuis un Pi, comme çà toute l'interface est gérée par le PI (ce qui serait une excellente idée pour l'IHM). En plus si t'as un PI tu peux se passer du cloud Spark et tout faire en cloud local avec le Pi (in premise comment ils disent) ;-)
