### ISSUE TITLE
Compilation impossible sur V1.1.1

### ISSUE THREAD

**Issue by ooii** [thibdct/programmateur-fil-pilote-wifi#3]
Bonjour,

J'ai la version 1.1.1 du programmateur. J'essaie de compiler le code en utilisant l'IDE Spark mais je rencontre l'erreur suivante :
`pilotes.cpp: FP7 was not declared in this scope`
En effet, quand je regarde `pilotes.h`, il semblerait que FP7 ne soit déclaré que pour la version 1.0. Est-ce vraiment le cas ?
Merci encore pour ce projet et merci d'avance pour vos réponses.

**Comment by thibdct** [comment]
Bonjour,
Pour la v1.1.1, on suppose que le relais est utilisé plutôt que le FP7. Le
code peut être modifié si besoin.

**Comment by ooii** [comment]
OK, merci.
J'ai donc commenté la partie qui teste si c'est la 1.0 pour setter le FP7 et je le sette à A0,A1. C'est bien ça ?
Merci encore.

**Comment by ooii** [comment]
Tout marche parfaitement. Merci encore.
