### ISSUE TITLE
Conseils pour montage non centralisé

### ISSUE THREAD

**Issue by gabriel-robert** [thibdct/programmateur-fil-pilote-wifi#6]
Bonjour,

Je suis dans un logement équipé de radiateurs électriques récents, mais malheureusement non cablés avec un fil pilote. L'ancienneté des gaines ne me permet pas sans risques d'en faire passer un. Néanmoins je souhaite pouvoir les contrôler via leur entrée fil pilote ( soit un contrôleur par radiateur ).

J'ai actuellement pensé utiliser un arduino et son ESP8266 ( voir un Adafruit Feather Huzzah ) pour programmer la chauffe. Mon soucis est que je ne suis pas sûr de moi quand il s'agit de manipuler de telles tensions.

En regardant votre montage je me dit qu'il y a moyen de bricoler quelque chose de sympa à base d'optotriacs.

J'ai un doute sur la manière dont je devrais relier tout ça : prendre en dérivation l'arrivée 220v de mon radiateur et de le faire passer dans ce circuit? Avec une protection par fusible? Ne serait-ce pas plus simple pour moi d'utiliser un relais, voir un un double relais afin de gérer les 6 ordres?

Merci d'avance, et bravo pour ce montage très propre!

**Comment by thibdct** [comment]
Bonjour,

Un NodeMCU par radiateur paraît peut-être surdimensionné. Néanmoins, il pourrait être sympa de créer un petit module spécifique. Basé sur la techno sans fil ULPNode par exemple. Bonne idée Charles @hallard ? 

En attendant, as-tu pensé aux Qubino? (http://www.maison-et-domotique.com/50104-piloter-son-radiateur-electrique-fil-pilote-avec-un-module-z-wave-qubino-zmnhja2/)?

**Comment by gabriel-robert** [comment]
C'est surdimensionné mais malheureusement, pas trop le choix.
Une autre solution, c'est le courant porteur, mais rien du tout pour les hobbyist... bien trop cher.

J'ai regardé les Qubino et consorts, mais la facture grimpe vite, car il faut également rajouter un boîtier de commande pour tout ça. L'avantage d'un module Wifi, au delà du coup dérisoire de nos jours, c'est que j'ai déjà du matériel qui tourne pour pouvoir le contrôler. Et ça rajoute un côté DIY qui m'intéresse vachement.

Le hic dans tout ça, c'est que je pars du principe que si je ne suis pas sûr de ce que je fais en touchant au 220v ( et à la sécurité de ma maison et de ses occupants ), je ne fais rien.

Ou sinon il me reste les WeMo switch avec un firmware cracké..

**Comment by sosandroid** [comment]
Hello

Effectivement pas beaucoup de choix pour ce cas. Il faut déporter la 
génération des signaux de fil pilote à partir de l'alim des radiateurs.

Le NodeMCU/Huzzah est un option wifi (attention lors d'un changement de 
fournisseur d'accès. Il faudra tous les reprogrammer pour assurer la 
connexion.
     - Avantage : on gère tout depuis le réseau TCP/IP
     - Aucun mode autonome puisque tout passe par le "serveur"

Une autre option est le Moteino qui fonctionne sur du 433 ou 868 MHz. 
C'est donc hors Wifi. Il faut donc ajouter une "passerelle" ethernet 
vers radio pour assurer le contrôle.
     - un mode autonome est possible puisque la "passerelle" peut 
écouter et émettre. Les capteurs peuvent donc lui parler directement
     - en cas de panne wifi, cela continue donc à fonctionner et c'est 
indépendant du provider de box (ethernet)
     - Un peu plus cher à mettre en oeuvre

Pour le 230v, cela se manipule avec des optitriacs ou des relais comme 
Remora. Faut juste un boitier correct pour mettre tout cela en sécurité 
et un fusible en entrée de 0,5A (largement suffisant normalement)

**Comment by gabriel-robert** [comment]
Merci pour les conseils. Je vais regarder de près les schematics et me lancer !
Je vous tiendrais au courant du montage.

**Comment by frco9** [comment]
Bonjour
Je suis également très intéressé par un montage décentralisé, avez-vous pu avancer sur le sujet @gabriel-robert  ?

**Comment by gabriel-robert** [comment]
Bonjour @frco9 
Non pas pour le moment, le temps de faire des travaux d'isolation plus urgents! Je me penche plus sérieusement sur le sujet courant février, je ne manquerais pas de vous tenir au courant!
